# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- bash: |
      sudo apt-get install libglfw3 libglfw3-dev -y -f
  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: Download libx on linux
- task: CMake@1
  displayName: 'Cmake ..'
  inputs:
    cmakeArgs: '..'
    
- task: CMake@1
  displayName: '--build . --config Debug'
  inputs:
    cmakeArgs: '--build . --config Debug'
