# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- bash: |
      sudo apt-get install xorg-dev libvulkan1 mesa-vulkan-drivers vulkan-utils -y -f
      wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
      sudo apt update
      sudo apt install vulkan-sdk

  condition: eq( variables['Agent.OS'], 'Linux')
  displayName: Download libx on linux
- task: CMake@1
  displayName: 'Cmake ..'
  inputs:
    cmakeArgs: '..'
    
- task: CMake@1
  displayName: '--build . --config Debug'
  inputs:
    cmakeArgs: '--build . --config Debug'
